-- +goose Up
CREATE TABLE ordered_products (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code uuid NOT NULL,
    user_uuid uuid NOT NULL,
    product_code integer NOT NULL,
    amount integer NOT NULL
);

-- +goose Down
DROP TABLE ordered_products;
