-- +goose Up
CREATE TABLE cart (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid uuid NOT NULL,
    product_code integer NOT NULL,
    amount integer NOT NULL
);
-- +goose Down
DROP TABLE cart;

