// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Order struct {
	OrderCode      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserUuid       uuid.UUID
	CompleteStatus string
}

type Product struct {
	ID          int32
	Name        string
	Price       string
	Category    string
	Image       sql.NullString
	Stock       int32
	Description sql.NullString
	Slug        string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt sql.NullTime
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Name           string
	Surname        string
	Phone          string
	Mobile         string
	Address        string
}
