INSERT INTO products (name, stock, price, description) VALUES ('Gloves', '32', '16.78', 'Incidunt debitis eum ea optio.');
INSERT INTO products (name, stock, price, description) VALUES ('Tuna', '6', '121.49', 'Eligendi quas eum voluptatem laborum quisquam porro.');
INSERT INTO products (name, stock, price, description) VALUES ('Cheese', '19', '177.33', 'Consequatur culpa consequatur.');
INSERT INTO products (name, stock, price, description) VALUES ('Playstation', '28', '51.78', 'Illo iure dignissimos dolore quaerat.');
INSERT INTO products (name, stock, price, description) VALUES ('Shoes', '8', '71.8', 'Aspernatur minima cum ipsum debitis officia incidunt.');
INSERT INTO products (name, stock, price, description) VALUES ('Keyboard', '22', '94.96', 'Nisi voluptatum aut hic quos sequi voluptates suscipit.');
INSERT INTO products (name, stock, price, description) VALUES ('Mouse', '34', '20.75', 'Inventore in sit ut facilis.');
INSERT INTO products (name, stock, price, description) VALUES ('Salad', '32', '73.39', 'Repudiandae incidunt delectus.');
INSERT INTO products (name, stock, price, description) VALUES ('Car', '1', '149.05', 'Occaecati vero ea eaque dignissimos tempore.');
INSERT INTO products (name, stock, price, description) VALUES ('Fish', '15', '48.78', 'Similique dolore et accusamus inventore.');
INSERT INTO products (name, stock, price, description) VALUES ('Windows', '49', '104.93', 'Perspiciatis animi perferendis voluptate officiis esse.');
INSERT INTO products (name, stock, price, description) VALUES ('Table', '17', '147.26', 'Maiores iste exercitationem voluptatum delectus at quis aliquam.');
INSERT INTO products (name, stock, price, description) VALUES ('Meat', '45', '78.66', 'Enim exercitationem nobis culpa iste cupiditate vitae commodi deleniti incidunt.');
INSERT INTO products (name, stock, price, description) VALUES ('Vest', '31', '11.55', 'Veniam eius sequi fugit explicabo doloremque occaecati itaque.');
INSERT INTO products (name, stock, price, description) VALUES ('Computer', '23', '185.2', 'Cum totam similique eius esse.');
INSERT INTO products (name, stock, price, description) VALUES ('Chips', '36', '3.23', 'Ullam nihil quas rem non hic laborum ut corporis tenetur.');
INSERT INTO products (name, stock, price, description) VALUES ('Ball', '17', '136.43', 'Explicabo molestias facilis.');
INSERT INTO products (name, stock, price, description) VALUES ('Hat', '42', '137.46', 'Exercitationem dignissimos quasi adipisci illo veniam delectus occaecati nesciunt laboriosam.');
INSERT INTO products (name, stock, price, description) VALUES ('Pizza', '4', '196.98', 'Minima ratione repellat architecto.');
INSERT INTO products (name, stock, price, description) VALUES ('Shirt', '6', '156.98', 'Ut nam minus molestiae.');
INSERT INTO products (name, stock, price, description) VALUES ('USB', '9', '174.79', 'Assumenda cumque delectus.');
