-- +goose Up
CREATE TABLE products(
        product_code INT GENERATED BY DEFAULT AS IDENTITY
        (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
        name TEXT NOT NULL,
        stock INT NOT NULL,
        description TEXT);
-- +goose Down
DROP TABLE products;
